// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqPMfc4dNVVW52HCYOedmGFVTayK5S_yo',
    appId: '1:115873275822:web:08f9ae2bfc00914d64723f',
    messagingSenderId: '115873275822',
    projectId: 'flavors2-testappignis-prod',
    authDomain: 'flavors2-testappignis-prod.firebaseapp.com',
    storageBucket: 'flavors2-testappignis-prod.appspot.com',
    measurementId: 'G-RNC5YDJ3RF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLgdMS0adxEXqyGH4l6qEeX9gT0eHVtw0',
    appId: '1:115873275822:android:7cb5631a2e46634064723f',
    messagingSenderId: '115873275822',
    projectId: 'flavors2-testappignis-prod',
    storageBucket: 'flavors2-testappignis-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6gdQkTiVMZyB7g4_hK-kgNqOrDvkA7r0',
    appId: '1:115873275822:ios:a12634a3d946f14164723f',
    messagingSenderId: '115873275822',
    projectId: 'flavors2-testappignis-prod',
    storageBucket: 'flavors2-testappignis-prod.appspot.com',
    iosClientId: '115873275822-fb9e9pge319u0f86eqshaqg4ln5ajem6.apps.googleusercontent.com',
    iosBundleId: 'com.ignisideas.flavors2testappignis',
  );
}
