// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa_2FdzezJWV8-_gKgebByxdVH4hkyF9s',
    appId: '1:314003444141:web:9f83365ec1eb098dcfd124',
    messagingSenderId: '314003444141',
    projectId: 'flavors2-testappignis-dev',
    authDomain: 'flavors2-testappignis-dev.firebaseapp.com',
    storageBucket: 'flavors2-testappignis-dev.appspot.com',
    measurementId: 'G-3NC6ML7ZJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLtDWLv--UcuPFM3Zd33rgI0a1Uz_3bw4',
    appId: '1:314003444141:android:f0114b99b1b90f88cfd124',
    messagingSenderId: '314003444141',
    projectId: 'flavors2-testappignis-dev',
    storageBucket: 'flavors2-testappignis-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2K2QO94-BRpHEDMpKzbuArwzbq7xixlA',
    appId: '1:314003444141:ios:4babddfc297f8fb3cfd124',
    messagingSenderId: '314003444141',
    projectId: 'flavors2-testappignis-dev',
    storageBucket: 'flavors2-testappignis-dev.appspot.com',
    iosClientId: '314003444141-09230i7crhvq5p1mt0djqvhqfnokqor5.apps.googleusercontent.com',
    iosBundleId: 'com.ignisideas.flavors2testappignis.dev',
  );
}
