// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjAbp9rMVO8XifMjbo6BwS3ySja2IwXBA',
    appId: '1:144129670943:web:0781e5441e21e119ff3a2a',
    messagingSenderId: '144129670943',
    projectId: 'flavors2-testappignis-uat',
    authDomain: 'flavors2-testappignis-uat.firebaseapp.com',
    storageBucket: 'flavors2-testappignis-uat.appspot.com',
    measurementId: 'G-YVM2XSG7M6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlAonjTKTdva39TBLDE07jQVHj8CDCkVI',
    appId: '1:144129670943:android:e7c0ca47118dcf25ff3a2a',
    messagingSenderId: '144129670943',
    projectId: 'flavors2-testappignis-uat',
    storageBucket: 'flavors2-testappignis-uat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_nGIy4O0F5vm_B49HtrxmM5-9aoaKsvI',
    appId: '1:144129670943:ios:48696532177028f3ff3a2a',
    messagingSenderId: '144129670943',
    projectId: 'flavors2-testappignis-uat',
    storageBucket: 'flavors2-testappignis-uat.appspot.com',
    iosClientId: '144129670943-u0h578opf5rqn3dtq3208tov1iqapnel.apps.googleusercontent.com',
    iosBundleId: 'com.ignisideas.flavors2testappignis.uat',
  );
}
